# Generated by Django 2.1.4 on 2018-12-07 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='time',
            field=models.TimeField(default=datetime.time(7, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('group_id', 'class_id', 'semester')},
        ),
    ]
