# Generated by Django 2.1.4 on 2018-12-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20181207_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
