# Generated by Django 2.1.4 on 2018-12-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20181207_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='classroom',
        ),
    ]
