# Generated by Django 2.1.4 on 2018-12-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20181207_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='date',
            new_name='dates',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_id',
            new_name='group_number',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='teacher',
            new_name='teachers',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='teacher_name',
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('group_number', 'class_id', 'semester')},
        ),
    ]
