# Generated by Django 2.1.4 on 2018-12-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_auto_20181207_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='dates',
            field=models.ManyToManyField(related_name='classes', to='schedules.Date'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(related_name='classes', to='schedules.Teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_in',
            field=models.ManyToManyField(related_name='students', to='schedules.Group'),
        ),
    ]
